import Head from 'next/head';
import HomePage from '../components/HomePage/HomePage';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sneho E-commerce </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* home page  */}

      <HomePage />

    </div>
  )
}
